### ISSUE TITLE
GUI报错Executable not found，cmd无效

### ISSUE THREAD

**Issue by SpaceThing** [LiuJiewenTT/Snowbreak_ServerSwitcher#1]
不知道是不是配置有问题？没太看懂使用说明
```
Product Name: 尘白禁区切服器
FrontEnd Name: 尘白禁区服务器切换器 - 前端
Author: LiuJiewenTT <liuljwtt@163.com>
Program Version: v1.1.0.5
Project Name: CBJQ_SS_FrontEnd-tk
Project Link: https://github.com/LiuJiewenTT/CBJQ_SS_FrontEnd-tk
License Type: MIT License
Build Info: B-I2 [2024-05-20 23:59:44.064305 +0800(中国标准时间) 141/21:1/Mon]

frontend_programdir: C:\Program Files\Snow\Snowbreak_ServerSwitcher\GUIs\CBJQ_SS_FrontEnd_tk-B-I2\CBJQ_SS_FrontEnd_tk-B-I2\_internal
Executable not found.
```
snow目录
![ctrpqi50 blq](https://github.com/LiuJiewenTT/Snowbreak_ServerSwitcher/assets/61451659/1364b9f0-e16c-40da-af75-428bfd501a24)
launcher目录
![mgpmq3gh rj3](https://github.com/LiuJiewenTT/Snowbreak_ServerSwitcher/assets/61451659/1ff610b5-8e7b-4333-9377-e22179dff37e)
worldwidee目录
![2day13bk qvk](https://github.com/LiuJiewenTT/Snowbreak_ServerSwitcher/assets/61451659/16ebe1ad-71fa-476f-ac2e-95432b3fc9e8)

**Comment by SpaceThing** [comment]
cmd创建的启动文件链接无效，文件路径过长中间省略号替代了正确路径，同时是否需要提前配置好startup-homeland.settings和startup-worldwide.settings两个文件？
![zhj5z01e 5dh](https://github.com/LiuJiewenTT/Snowbreak_ServerSwitcher/assets/61451659/cdb474e8-ef9d-4a8c-855f-c46e2ee09017)

**Comment by SpaceThing** [comment]
cmd无法创建启动器的链接，“拒绝访问”
![sivnrktb i2n](https://github.com/LiuJiewenTT/Snowbreak_ServerSwitcher/assets/61451659/5393db61-87d7-4020-9d9b-7e345c7d4afb)

**Comment by LiuJiewenTT** [comment]
存储在c盘本来就容易遇到权限不足的问题，用管理员权限启动试试

**Comment by SpaceThing** [comment]
右键管理员运行直接闪退，我试试先启动管理员cmd再运行bat

**Comment by LiuJiewenTT** [comment]
bat程序就是要从命令行执行的，启动一个带管理员权限的命令行试试

**Comment by SpaceThing** [comment]
运行成功了，启动文件我手动准备了startup-homeland.settings和startup-worldwide.settings，不然创建的symlink好像有问题
但是国际服启动器运行之后点检查更新，会重启启动器同时替换国际服启动器symlink为国服启动器exe😭

**Comment by LiuJiewenTT** [comment]
检查了一下，发漏了gui的配套config。cwd需要设置成..\\..\\..\\。详细配置教程见：【尘白禁区切服器 - 安装及美化-哔哩哔哩】 https://b23.tv/AMxn2w0

**Comment by LiuJiewenTT** [comment]
启动器更新不影响的啊，怎么回事？重命名都完成了？话说你gui现在能用了吗？

**Comment by SpaceThing** [comment]
gui可以了，json要转义成..\\..\\..\\，但是启动器会自动更新并替换🤣
这是新版启动器加了监测吗

**Comment by LiuJiewenTT** [comment]
> gui可以了，也是需要右键管理员权限，json要转义成..\\..\\..\\
> 但是启动器会自动更新并替换🤣这是新版启动器加了检测吗

gui能用了就没那么多事了，反正启动器更新不影响其他启动器，也不影响symlink。
启动器的更新是尘白那边自己的功能，重命名不影响其更新替换。我不知道你说的检测是什么，反正尘白官方就是会让启动器升级成最新(除非你不联网它检查不到)。

**Comment by LiuJiewenTT** [comment]
> gui可以了，也是需要右键管理员权限，json要转义成..\\..\\..\\
> 但是启动器会自动更新并替换🤣这是新版启动器加了检测吗
> 还是说因为我没有给国际服的游戏资源另开文件夹，和国服共用了？

国际服的资源和国服的资源不能共用啊，哥们！你想每次切换下载20GB吗？看上面的视频教程配置吧，那个是我现在在用的的配置过程实录。

**Comment by SpaceThing** [comment]
我的意思是国际服启动器打开后自动检测更新，并且强制重启，重启后启动器被替换为官服版
而且这个好像跟切服器无关，直接启动launcher目录的国际服启动器也会被替换
![w2i520qr glx](https://github.com/LiuJiewenTT/Snowbreak_ServerSwitcher/assets/61451659/e49578e4-fe43-4e0d-8940-d3c6b4123ab8)

**Comment by SpaceThing** [comment]
> > gui可以了，也是需要右键管理员权限，json要转义成..\..\..\
> > 但是启动器会自动更新并替换🤣这是新版启动器加了检测吗
> > 还是说因为我没有给国际服的游戏资源另开文件夹，和国服共用了？
> 
> 国际服的资源和国服的资源不能共用啊，哥们！你想每次切换下载20GB吗？看上面的视频教程配置吧，那个是我现在在用的的配置过程实录。

我的，当时看这一段理解错了
![0m2xrxib rwe](https://github.com/LiuJiewenTT/Snowbreak_ServerSwitcher/assets/61451659/b691213b-ba62-4581-b78e-b55a2c8f27e2)

**Comment by LiuJiewenTT** [comment]
> 我的意思是国际服启动器打开后自动检测更新，并且强制重启，重启后启动器被替换为官服版
> 而且这个好像跟切服器无关，直接启动launcher目录的国际服启动器也会被替换
> ![w2i520qr glx](https://github.com/LiuJiewenTT/Snowbreak_ServerSwitcher/assets/61451659/e49578e4-fe43-4e0d-8940-d3c6b4123ab8)
> 

啊？你有魔法玩国际服吧？应该不至于下错，我这个版本更新都是对的。国际服的图标倒是确实和国服统一了

**Comment by SpaceThing** [comment]
重新试了下，可能是我操作bug，现在没问题了

**Comment by LiuJiewenTT** [comment]
哥们，考虑一下把游戏移出C盘吧，你之前说的启动器乱掉的问题我有点想法了，大概和我刚遇到的问题是同一个问题：https://github.com/LiuJiewenTT/Snowbreak_ServerSwitcher/discussions/3 。现在我还在查找新的解决方案。Issue: https://github.com/LiuJiewenTT/Snowbreak_ServerSwitcher/issues/4
